SBVT-1486: test

diff --git a/.github/workflows/typescript-test.yml b/.github/workflows/typescript-test.yml
--- a/.github/workflows/typescript-test.yml
+++ b/.github/workflows/typescript-test.yml
@@ -28,8 +28,22 @@ jobs:
         working-directory: ./test/typescript-test
 
       - name: Setup visualtest
-        run: npx visualtest-setup
+        run: npx visualtest-setup > visualtest-logs.txt
         working-directory: ./test/typescript-test
+
+      - name: Verify console logs
+        run: |
+          # Read the contents of the log file
+          logs=$(cat visualtest-logs.txt)
+
+          # Check if the logs contain a specific string or pattern
+          if [[ $logs =~ "expected log string" ]]; then
+            echo "Log string found!"
+          else
+            echo "Log string not found."
+            exit 1  # Consider failing the workflow if the log is not found
+          fi
+      
 
       - name: Cypress run
         uses: cypress-io/github-action@v5
